import "./globals.css";
import { Darker_Grotesque } from "next/font/google";
import { TransactionProvider } from "./provider";

const fontFamily = Darker_Grotesque({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <TransactionProvider>
        <body className={fontFamily.className}>{children}</body>
      </TransactionProvider>
    </html>
  );
}
